<?php

function licensed_vendors_menu() {
    
    $items = [];

    $items['licensed-vendors'] = array(
        'title' => 'Licensed Vendors',
        'page callback' => 'serve_licensed_vendors_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

/*
  
  @param $country 
  @returns $region | boolean 

*/

function get_country_region($country){

        $found_region = false;

        $map_countries_to_regions = [
                                       "Africa" =>["Algeria","DZ","DZA","Angola","AO","AGO","Cote d'Ivoire","Zambia"],
                                       "Asia" =>  ["Afghanistan","AF","AFG", "Hong Kong","HK","India","IN","Indonesia","Japan","Korea",
                                       "Malaysia","Philippines","Taiwan","Thailand"],
                                       "Europe" => ["Albania","AL","ALB","Andorra","AD","AND","Belgium","Denmark","England","Finland","Germany","Guernsey","Italy","Netherlands","Norway","Spain","Sweden","Switzrland"],
                                       "North america" => ["Canada","United States","Mexico"],
                                       "Oceania" => ["American Samoa","AS","ASM","Australia","New Zealand"],
                                       "South America" => ["Argentia","Brazil","Peru"]
                                    ];
        
       foreach( $map_countries_to_regions as $region => $country_array ){

            if( in_array(trim($country), $country_array) ){

                  $found_region = z($region);
                  break;
            } 
       }

       return $found_region;
   }

function serve_licensed_vendors_page() { 

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'licensed_vendor');

  $result = $query->execute();

  if (isset($result['node'])) {
  
    $licensed_vendors_nids = array_keys($result['node']);
    $licensed_vendors = entity_load('node', $licensed_vendors_nids);

  } 

  $vendors_to_display = [];

  foreach($licensed_vendors as $vendor) {

    // get the zone from the vendor's country and add that as a field to the given vendor node

    if(isset($vendor->field_lv_country['und'][0]['value'])) {

             $lv_region = get_country_region($vendor->field_lv_country['und'][0]['value']); 

             if($lv_region) {
   
                     $vendor->region = $lv_region;
                     $vendors_to_display[] = $vendor;
             }
             else {
                     
                     // need to wrap the below in a t() function 
                     watchdog('licensed_vendors','Region could not be found for: @country',
                       array('@country' => $vendor->field_lv_country['und'][0]['value']),
                       WATCHDOG_INFO
                      ); 
             }     
         }
 }


  $html = theme('licensed_vendors_page',
                
                 array( 
                        "vendors" => $vendors_to_display
                      )
               );
             
  return $html;
}

/**
 * Implements hook_theme().
 */
function licensed_vendors_theme($existing, $type, $theme, $path) {
  
  return array(

      'licensed_vendors_page' => array(
      'template' => 'licensed-vendors-page',
    ),

  );
  
}


