<?php

function hello_world_menu() {
    $items = array();

    $items['tester/hello_world'] = array(
        'title' => 'Hello World Test //DWC',
       // 'page callback' => 'say_hello_world',
        'page callback' => 'my_static_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function say_hello_world() {
    $vars = array();
    $vars['type']="ul";
    $vars['title'] = "";
    $vars['attributes']=array("");
    $vars['items'][0]="This is a simple proof of concept module";

    return theme_item_list($vars);
}

function my_static_page() { 
  $html = theme('html_page', 
                 array( 
                        "fruits"  => array("apple","pear","banana"),
                        "veggies" => array("beets","onions","mushrooms") // works - we can access these array items in template
                      ));

 // $html .= '<h1>Can I add on some html this way ?</h1>'; // YUP ! works.

  return $html;
}

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path) {
  return array(
    'html_page' => array(
      'template' => 'html-page',
    ),
  );
}